apiVersion: argoproj.io/v1alpha1
kind: AppProject

metadata:
  name: dpf-project
  namespace: argocd

spec:

  description: DPF Platform Project

  sourceRepos:
  - '*'

  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc

  clusterResourceWhitelist:
  - group: '*'
    kind: '*'

  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
