apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: cert-manager
  namespace: argocd

spec:

  project: dpf-platform

  source:
    repoURL: https://github.com/romain617/devops-platform.git
    targetRevision: main
    path: platform-components/cert-manager

  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
