apiVersion: apps/v1
kind: Deployment

metadata:
  name: local-path-provisioner
  namespace: local-path-storage

spec:

  replicas: 1

  selector:
    matchLabels:
      app: local-path-provisioner

  template:

    metadata:
      labels:
        app: local-path-provisioner

    spec:

      serviceAccountName: local-path-provisioner-service-account

      containers:

      - name: local-path-provisioner

        image: rancher/local-path-provisioner:v0.0.31

        command:
        - local-path-provisioner
        - start

        env:

        - name: CONFIG
          valueFrom:
            configMapKeyRef:
              name: local-path-config
              key: config.json

        volumeMounts:

        - name: config-volume
          mountPath: /etc/config

      volumes:

      - name: config-volume

        configMap:

          name: local-path-config
