cat <<'EOF' > platform-components/storage/manifests/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole

metadata:
  name: local-path-provisioner-role

rules:

- apiGroups:
  - ""
  resources:
  - nodes
  - persistentvolumes
  - persistentvolumeclaims
  - pods
  - events
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - patch
  - update

- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch

- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - watch


---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding

metadata:
  name: local-path-provisioner-role-binding

subjects:

- kind: ServiceAccount
  name: local-path-provisioner-service-account
  namespace: local-path-storage

roleRef:

  kind: ClusterRole
  name: local-path-provisioner-role
  apiGroup: rbac.authorization.k8s.io
EOF
