apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:

  - setup

  - prometheusOperator-serviceAccount.yaml
  - prometheusOperator-clusterRole.yaml
  - prometheusOperator-clusterRoleBinding.yaml
  - prometheusOperator-deployment.yaml
  - prometheusOperator-service.yaml
